# Generated by Django 3.2.7 on 2022-01-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_phone_no_customer_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
