# Generated by Django 3.2.7 on 2022-02-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_rental_booking_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_booking',
            name='vehicle_type',
        ),
    ]
