# Generated by Django 3.2.7 on 2022-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_rental_booking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_booking',
            name='vehicle_type',
            field=models.CharField(choices=[('1', 'bike'), ('2', 'car'), ('3', 'boat'), ('4', 'van'), ('5', 'scooter')], default='1', max_length=50),
        ),
    ]
