# Generated by Django 3.2.7 on 2022-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220203_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=100)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('vehicle_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='rental_booking',
        ),
    ]
