# Generated by Django 3.2.7 on 2022-02-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20220203_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rental',
            table='app1_rental',
        ),
    ]
